389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
Hide Company Tags Google
Hide Tags Hash Table Bit Manipulation
Hide Similar Problems (E) Single Number

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
// O(m + n)
// corner case: "a","aa" return 'a', map[a] = 1, -> 0 -> -1
var findTheDifference = function(s, t) {
    if (s === null || t === null || t.length === 0) {
        return '';
    }
    let map = new Map();
    for (let i = 0; i < s.length; i++) {
        if (map.has(s.charAt(i))) {
            map.set(s.charAt(i), map.get(s.charAt(i)) + 1);
        } else {
            map.set(s.charAt(i), 1);
        }
    }
    for (let j = 0; j < t.length; j++) {
        // three cases: key doesn't exist, return key; key exist, value--, if value === -1, return key too
        if (map.has(t.charAt(j))) {
            map.set(t.charAt(j), map.get(t.charAt(j)) - 1);
            if (map.get(t.charAt(j)) === -1) {
                return t.charAt(j);
            }
        } else {
            return t.charAt(j);
        }
    }
    return '';
};
